# Generated by Django 6.1 on 2026-09-21 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('telescopes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('catalog_id', models.CharField(blank=True, help_text='Catalog identifier (e.g. NGC 224, HD 209458).', max_length=50)),
                ('right_ascension', models.CharField(help_text='RA in HHh MMm SS.Ss format.', max_length=30)),
                ('declination', models.CharField(help_text='DEC in ±DD° MM\' SS.S" format.', max_length=30)),
                ('object_class', models.CharField(choices=[('galaxy', 'Galaxy'), ('nebula', 'Nebula / HII Region'), ('star', 'Star / Star Cluster'), ('exoplanet', 'Exoplanet Host'), ('solar_system', 'Solar System Object'), ('quasar', 'Quasar / AGN'), ('other', 'Other / Unknown')], default='star', max_length=20)),
                ('magnitude', models.FloatField(blank=True, help_text='Visual magnitude.', null=True)),
                ('distance_ly', models.FloatField(blank=True, help_text='Estimated distance in light-years.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Observation Target',
                'verbose_name_plural': 'Observation Targets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObservationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(help_text='Scientific rationale and methodology of the observing program.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(choices=[(1, "P1 - Director's Discretionary"), (2, 'P2 - Target of Opportunity'), (3, 'P3 - Queue Observer'), (4, 'P4 - Long-Term Program')], default=3)),
                ('total_time_hours', models.FloatField(default=1.0, help_text='Total allocated observing time in hours.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Principal Investigator')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observation Proposal',
                'verbose_name_plural': 'Observation Proposals',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScienceQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_time', models.FloatField(help_text='Exposure duration in seconds.')),
                ('number_of_frames', models.PositiveIntegerField(default=1)),
                ('filter_name', models.CharField(default='V', max_length=30)),
                ('queue_status', models.CharField(choices=[('queued', 'Queued / Waiting'), ('executing', 'Executing'), ('completed', 'Completed'), ('aborted', 'Aborted / Failed'), ('paused', 'Paused')], default='queued', max_length=20)),
                ('queue_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='observations.observationproposal')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.observationtarget')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telescopes.telescope')),
            ],
            options={
                'verbose_name': 'Science Queue Item',
                'verbose_name_plural': 'Science Queue Items',
                'ordering': ['queue_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExposureRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits_file_ref', models.CharField(blank=True, help_text='FITS file path or archive reference.', max_length=200)),
                ('signal_to_noise', models.FloatField(blank=True, help_text='Achieved SNR.', null=True)),
                ('seeing_arcsec', models.FloatField(blank=True, help_text='Measured atmospheric seeing in arcseconds.', null=True)),
                ('sky_transparency', models.CharField(choices=[('photometric', 'Photometric'), ('clear', 'Clear'), ('thin_cloud', 'Thin Clouds'), ('variable', 'Variable')], default='clear', max_length=20)),
                ('airmass', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='observations.sciencequeueitem')),
            ],
            options={
                'verbose_name': 'Exposure Run Log',
                'verbose_name_plural': 'Exposure Run Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
