# Generated by Django 6.1 on 2026-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationtarget',
            name='epoch',
            field=models.CharField(default='J2000.0', help_text='Astronomical coordinate epoch.', max_length=20),
        ),
        migrations.AddField(
            model_name='observationtarget',
            name='observation_date',
            field=models.DateField(blank=True, help_text='Observation / entry date.', null=True),
        ),
        migrations.AddField(
            model_name='observationtarget',
            name='recommended_filter',
            field=models.CharField(default='V (550nm)', help_text='Filter used / recommended.', max_length=50),
        ),
    ]
