# Generated by Django 6.1 on 2026-09-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observationtarget_epoch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciencequeueitem',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='sciencequeueitem',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='sciencequeueitem',
            name='target',
        ),
        migrations.RemoveField(
            model_name='sciencequeueitem',
            name='telescope',
        ),
        migrations.RemoveField(
            model_name='exposurerunlog',
            name='queue_item',
        ),
        migrations.AddField(
            model_name='exposurerunlog',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='observations.observationtarget'),
        ),
        migrations.DeleteModel(
            name='ObservationProposal',
        ),
        migrations.DeleteModel(
            name='ScienceQueueItem',
        ),
    ]
