# Generated by Django 6.1 on 2026-09-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_remove_sciencequeueitem_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtarget',
            name='declination',
            field=models.CharField(blank=True, default='+00° 00\' 00.0"', help_text='DEC in ±DD° MM\' SS.S" format.', max_length=30),
        ),
        migrations.AlterField(
            model_name='observationtarget',
            name='right_ascension',
            field=models.CharField(blank=True, default='00h 00m 00.0s', help_text='RA in HHh MMm SS.Ss format.', max_length=30),
        ),
    ]
