# Generated by Django 6.1 on 2026-09-22 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='User name or Anonymous', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('ui_ux', 'UI / UX Design'), ('feature', 'Feature Request'), ('bug', 'Bug / System Issue'), ('telescope_control', 'Telescope Control & Telemetry'), ('performance', 'Performance'), ('general', 'General Feedback')], default='general', max_length=30)),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Allow feedback to be displayed in public feedback showcase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Feedback',
                'verbose_name_plural': 'Site Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
