# Generated by Django 6.1 on 2026-09-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telescopes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Instrument Name.', max_length=150)),
                ('code', models.CharField(help_text='Short identifier code.', max_length=20, unique=True)),
                ('instrument_type', models.CharField(choices=[('spectrograph', 'Optical Spectrograph'), ('ccd_imager', 'Direct CCD Imager'), ('ir_camera', 'Near-Infrared Camera'), ('photometer', 'Fast Photometer'), ('polarimeter', 'Imaging Polarimeter'), ('adaptive_optics', 'Adaptive Optics Unit')], default='spectrograph', max_length=30)),
                ('status', models.CharField(choices=[('online', 'Online / Science Ready'), ('calibrating', 'Running Calibration'), ('standby', 'Thermal Standby'), ('maintenance', 'Maintenance Lock'), ('error', 'Cryo/Sensor Alarm')], default='standby', max_length=20)),
                ('detector_temp', models.FloatField(default=-110.5, help_text='Current CCD detector temperature (°C).')),
                ('setpoint_temp', models.FloatField(default=-115.0, help_text='Target cooling setpoint (°C).')),
                ('vacuum_pressure', models.FloatField(default=1.2e-06, help_text='Dewar vacuum pressure in mbar.')),
                ('cooling_power_percent', models.FloatField(default=68.5, help_text='Cooler duty cycle percentage.')),
                ('gain', models.FloatField(default=1.5, help_text='CCD gain in e-/ADU.')),
                ('binning', models.CharField(default='1x1', help_text='Pixel binning mode (e.g., 1x1, 2x2).', max_length=10)),
                ('readout_speed', models.CharField(default='100 kHz (Low Noise)', max_length=50)),
                ('active_filter', models.CharField(default='V (550nm)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telescope', models.ForeignKey(help_text='Mounted host telescope.', on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='telescopes.telescope')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='°C', max_length=20)),
                ('current_value', models.FloatField()),
                ('min_warning', models.FloatField()),
                ('max_warning', models.FloatField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Instrument Sensor',
                'verbose_name_plural': 'Instrument Sensors',
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='°C', max_length=20)),
                ('status_flag', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical Alarm')], default='normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Telemetry Log',
                'verbose_name_plural': 'Telemetry Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FilterWheelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('filter_name', models.CharField(max_length=50)),
                ('central_wavelength', models.FloatField(help_text='Central wavelength in nm.')),
                ('bandwidth', models.FloatField(help_text='FWHM Bandwidth in nm.')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_wheel', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Filter Wheel Slot',
                'verbose_name_plural': 'Filter Wheel Configurations',
                'ordering': ['slot_number'],
                'unique_together': {('instrument', 'slot_number')},
            },
        ),
    ]
