# Generated by Django 6.1 on 2026-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('telescopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_telescopes',
            field=models.ManyToManyField(blank=True, help_text='Telescopes this observer is authorized to view and control.', related_name='assigned_observers', to='telescopes.telescope'),
        ),
    ]
