# Generated by Django 6.1 on 2026-09-21 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('telescopes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_type', models.CharField(choices=[('bias', 'Bias Frame'), ('dark', 'Dark Frame'), ('flat', 'Flat Field'), ('wavelength', 'Wavelength Calibration Lamp'), ('standard_star', 'Standard Star Flux Calibration'), ('focus', 'Focus / PSF Calibration'), ('pointing', 'Pointing Model Calibration')], max_length=30)),
                ('standard_lamp_or_target', models.CharField(blank=True, help_text='Arc lamp ID, standard star name, or flat source.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_run', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Calibration Log',
                'verbose_name_plural': 'Calibration Logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the fault or maintenance required.')),
                ('severity', models.CharField(choices=[('critical', 'CRITICAL - System Halt'), ('high', 'HIGH - Science Impact'), ('medium', 'MEDIUM - Degraded Mode'), ('low', 'LOW - Routine / Scheduled')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='instruments.instrument')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
                ('telescope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='telescopes.telescope')),
            ],
            options={
                'verbose_name': 'Maintenance Ticket',
                'verbose_name_plural': 'Maintenance Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
