# Generated by Django 6.1 on 2026-09-21 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telescopes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateSolveRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ra_deg', models.FloatField(default=0.0)),
                ('target_dec_deg', models.FloatField(default=0.0)),
                ('fov_deg', models.FloatField(default=20.0)),
                ('solved_ra_deg', models.FloatField(blank=True, null=True)),
                ('solved_dec_deg', models.FloatField(blank=True, null=True)),
                ('pixel_scale_arcsec', models.FloatField(default=35.15)),
                ('rotation_angle_deg', models.FloatField(default=0.0)),
                ('matched_stars_count', models.IntegerField(default=0)),
                ('solution_time_sec', models.FloatField(default=0.42)),
                ('ra_error_arcmin', models.FloatField(default=0.0)),
                ('dec_error_arcmin', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('solving', 'Solving in Progress'), ('success', 'Solved Successfully'), ('failed', 'Solving Failed')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telescope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_solves', to='telescopes.telescope')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plate Solve Run',
                'verbose_name_plural': 'Plate Solve Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
