# Generated by Django 6.1 on 2026-09-21 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the observatory telescope.', max_length=150)),
                ('code', models.CharField(help_text='Short system code identifier.', max_length=20, unique=True)),
                ('aperture', models.FloatField(help_text='Primary mirror aperture diameter in meters.')),
                ('focal_ratio', models.CharField(default='f/9', help_text='Focal ratio (e.g., f/9, f/11).', max_length=10)),
                ('mount_type', models.CharField(choices=[('alt_az', 'Alt-Azimuth Mount'), ('german_eq', 'German Equatorial Mount'), ('fork_eq', 'Fork Equatorial Mount')], default='alt_az', max_length=20)),
                ('location', models.CharField(default='IIA Observatory Site', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online / Ready'), ('slewing', 'Slewing Target'), ('tracking', 'Tracking Target'), ('idle', 'Parked / Standby'), ('maintenance', 'Maintenance Mode'), ('fault', 'System Fault')], default='idle', max_length=20)),
                ('right_ascension', models.CharField(default='00h 00m 00.0s', max_length=30)),
                ('declination', models.CharField(default='+00° 00\' 00.0"', max_length=30)),
                ('epoch', models.CharField(default='J2000', max_length=10)),
                ('focus_position', models.FloatField(default=12.5, help_text='Focuser position in mm.')),
                ('dome_status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('parkov', 'Parked'), ('rotating', 'Rotating / Slewing')], default='closed', max_length=20)),
                ('dome_azimuth', models.FloatField(default=0.0, help_text='Dome azimuth angle in degrees.')),
                ('primary_mirror_temp', models.FloatField(default=5.2, help_text='Mirror temperature in °C.')),
                ('ambient_temp', models.FloatField(default=2.1, help_text='Ambient dome air temperature in °C.')),
                ('humidity', models.FloatField(default=35.0, help_text='Relative humidity percentage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telescope',
                'verbose_name_plural': 'Telescopes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TelescopeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('slew', 'Slew Execution'), ('track_start', 'Tracking Started'), ('track_stop', 'Tracking Stopped'), ('dome_open', 'Dome Opened'), ('dome_close', 'Dome Closed'), ('fault', 'Hardware Fault'), ('maintenance', 'Maintenance Action')], default='slew', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='telescopes.telescope')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telescope Log',
                'verbose_name_plural': 'Telescope Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
