# Generated by Django 6.1 on 2026-09-22 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescopes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelescopeDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Observatory Chat'), ('observation', 'Observation Logs & Targets'), ('hardware', 'Hardware & Mount Operations'), ('optics', 'Optics & Focusing'), ('software', 'Software & Plate Solving'), ('maintenance', 'Maintenance Notes')], default='general', max_length=30)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telescope', models.ForeignKey(help_text='Separate telescope for this discussion thread', on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='telescopes.telescope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telescope_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telescope Discussion',
                'verbose_name_plural': 'Telescope Discussions',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelescopeDiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='telescopes.telescopediscussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telescope_discussion_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telescope Discussion Reply',
                'verbose_name_plural': 'Telescope Discussion Replies',
                'ordering': ['created_at'],
            },
        ),
    ]
